language: python
python:
 - "3.7"

install: pip install -r requirements-dev.txt

matrix:
  include:
    - name: Black formatter
      script: black -v --check .
      after_failure: scripts/travis_notify_unformatted.sh
